name: clima
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  geolocator: ^8.2.0
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  timezone: ^0.8.0
  date_format: ^2.0.6
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  connectivity_plus: ^1.0.6
  translator: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
          weight: 900